version: 2.0
jobs:
  build:
    docker:
      - image: circleci/elixir:1.7.4
    environment:
      MIX_ENV: test
    working_directory: ~/zmq_ex
    steps:
      - checkout
      - run:
          name: mix local.*
          command: |
            mix local.rebar --force
            mix local.hex --force

      - restore_cache:
          keys:
            - zmq_ex-deps-{{ checksum "mix.lock" }}
      - run: mix deps.get
      - save_cache:
          key: zmq_ex-deps-{{ checksum "mix.lock" }}
          paths:
            - deps/

      - run: mix format --check-formatted
      - run: mix compile
      - run: mix credo --strict
      - run:
          name: mix test (coveralls.circle)
          command: |
            mkdir -p ./test-results/mix
            mix coveralls.circle
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results

      - restore_cache:
          keys:
            - zmq_ex-plt-{{ .BuildNum }}
            - zmq_ex-plt-
      - run:
          name: restore plts
          command: |
            mkdir -p ./plt
            touch ./plt/files
            mv ./plt/* _build/test/
      - run: mix dialyzer
      - run:
          name: save plts
          command: |
            cp _build/test/*.plt ./plt
      - save_cache:
          key: zmq_ex-plt-{{ .BuildNum }}
          paths:
            - ./plt/

