version: 2.0
jobs:
  build:
    docker:
      - image: circleci/elixir:1.7
    environment:
      MIX_ENV: test
    working_directory: ~/zmq_ex
    steps:
      - checkout
      - restore_cache:
          keys:
            - zmq_ex-deps-{{ checksum "mix.lock" }}
      - restore_cache:
          keys:
            - zmq_ex-plt-{{ checksum "mix.lock" }}
            - zmq_ex-plt-

      - run: mkdir -p ./test-results/mix
      - run: mix local.rebar --force
      - run: mix local.hex --force
      - run: mix deps.get
      - run: mix format --check-formatted
      - run: mix coveralls.circle
      - run: mix credo --strict

      - run: mix dialyzer

      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results

      - save_cache:
          key: zmq_ex-deps-{{ checksum "mix.lock" }}
          paths:
            - deps/
      - save_cache:
          key: zmq_ex-plt-{{ checksum "mix.lock" }}
          paths:
            - _build/test/dialyxir_erlang-21.1.1_elixir-1.7.3_deps-test.plt

