version: 2.0
jobs:
  build:
    docker:
      - image: circleci/elixir:1.7.3
    environment:
      MIX_ENV: test
    working_directory: ~/zmq_ex
    steps:
      - checkout
      - run:
          name: mix local.*
          command: |
            mix local.rebar --force
            mix local.hex --force

      - restore_cache:
          keys:
            - zmq_ex-deps-{{ checksum "mix.lock" }}
      - run: mix deps.get

      - run: mix format --check-formatted
      - run: mix compile
      - run: mix credo --strict

      - run:
          name: mix test (coveralls.circle)
          command: |
            mkdir -p ./test-results/mix
            mix coveralls.circle

      - restore_cache:
          keys:
            - zmq_ex-plt-{{ checksum "mix.lock" }}
            - zmq_ex-plt-
      - run: mix dialyzer

      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-results

      - save_cache:
          key: zmq_ex-deps-{{ checksum "mix.lock" }}
          paths:
            - deps/
      - save_cache:
          key: zmq_ex-plt-{{ checksum "mix.lock" }}
          paths:
            - _build/test/dialyxir_erlang-21.1.1_elixir-1.7.3_deps-test.plt

